apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-container
          image: gcr.io/alien-hour-431301-a4/flask-app:latest
          ports:
            - containerPort: 5000
            - containerPort: 5001
          env:
            - name: MY_SECRET_KEY
              value: asdvasbasd
            - name: DEPLOY_DATABASE_URL
              value: postgresql+psycopg2://myuser:mypassword@db-service:5432/mydb
